#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx

service nginx start
sed -i 's/#listen 80;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
