#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update && sudo apt-get install nginx

sudo service nginx start

sudo touch /var/www/html/index.html

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart
