#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on


sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo echo 'Hello World!' > /var/www/html/index.html
sudo touch /etc/nginx/html/404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo printf %s "server {
	listen 80;
	listen [::]:80 default_server;
	add_header X-Served-By $HOSTNAME;

	root   /etc/ngnix/html;
	index  index.html index.htm;

	location /redirect_me {
	     return 301 http://cuberule.com/;
	}

	error_page 404 /404.html;
	location /404 {
	   root /etc/nginx/html;
	   internal;
   	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
