#!/usr/bin/env bash
# configures a server and fixes a bug : Ubuntu container’s Nginx installation not listening on port 80

# service nginx restart
apt-get update -y
apt-get install nginx -y
sudo service nginx enable
sudo service nginx start
