#!/usr/bin/env bash
# fix short and sweet
sudo sed -i 's/user www-data/user nginx/ s/80/8080/g' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
